### PR TITLE
Update README.md - fixing broken link to the API doc

### PR DESCRIPTION
**Pull request by jhuska**
I guess that with CNAME change it broke.

### CODE REVIEW

**Comment by bleathem** [comment]
The problem with this fix is it breaks the API link when running the demo locally.  This can cause confusion when one is working on updating the API docs.

**Comment by lfryc** [comment]
I think we can do some string replacement when compiling the page, because AFAIK there is no bullet-proof solution.

**Comment by bleathem** [comment]
+1.  We are already doing such string replacement here:
https://github.com/richwidgets/richwidgets/blob/master/Gruntfile.js#L517

``` javascript
        postprocess: function(content) {
          // replace links to github markdown files with relative links to html versions of the files
          content = content.replace(/https:\/\/github\.com\/richwidgets\/richwidgets\/blob\/master\/([a-zA-Z]*)\.md/g, function(match, name) {
            return name === 'README' ? 'about.html' : name.toLowerCase() + '.html';
          });
          return content;
        }
```

**Comment by bleathem** [comment]
Re-closing, leaving it as it is.  This is just the link in the paragraph, the top toolbar link correctly uses the relative path, which is what one would use in development.

**Pull request closed without merging**
