### PR TITLE
Sauce Labs configuration so that test can be run in multiple browsers (issue #28)

### PR DESCRIPTION
**Pull request by ppitonak**

### CODE REVIEW

**Comment by lfryc** [comment]
Pavol, could you please update the README with section on how to run tests on SauceLabs?

**Comment by bleathem** [comment]
This issue duplicates #28.

@ppitonak you can reference github issues in your commits/PRs with the syntax `resolves #28`.  See:
https://help.github.com/articles/closing-issues-via-commit-messages

**Comment by lfryc** [comment]
@bleathem I have tried and sending pull request opens new issue no matter if you include issue number. Still referencing an issue is good to allow us to find upstream issue (as Pavol did).

**Comment by lfryc** [comment]
I have updated TESTS.md accordingly.

**Comment by bleathem** [comment]
@lfryc we may want to consider using the `hub` tool to attach PRs to existing issues:
https://github.com/github/hub

Let's discuss this via the mail list.

**Pull request closed without merging**
