### PR TITLE
Adopt Common Visual Style

### PR DESCRIPTION
**Pull request by bleathem**
Work in a feature branch.

Bootstrap 3 branch:
https://github.com/rhamilto/rcue/tree/bootstrap-3

Presentation:
http://uxd-rcue.rhcloud.com/

### CODE REVIEW

**Comment by lfryc** [comment]
@bleathem I have resolved all issues now. Could you please review my approach before merging to master?

Note that we need to resolve failing tests (I suspect they are issues caused by style attribute difference).

**Comment by bleathem** [comment]
This looks really good @lfryc.  I'm glad we were able to include RCUE without forking it.  What I don't like is how richwidgets seems to now be "married" to RCUE.  While out-of-scope for 0.1, I think we should investigate what we have to do to make the bootstrap skin skinnable.  This would involve:

1) Dynamically (perhaps a LESS variable) defining which skin to include
2) Externalizing any custom modifications into a skin-specific file (in our case rcue).

Additionally it would be nice to enable the demo to switch between the skins (or perhaps have a 2nd demo rooted under the skin name: `http://richwidgets.io/some-skin`)

Let's go ahead and merge these changes and discuss themability in the context of 0.2

**Comment by lfryc** [comment]
+1 agree

I will create new issue and schedule it to 0.2.

I will merge and upload an updated demo.

**Comment by lfryc** [comment]
Demo updated: http://www.richwidgets.io/

**Pull request closed without merging**
